name: Deployment Back Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: bash
    #     working-directory: ./back
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: './back'
          sparse-checkout-cone-mode: false
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '>=16'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build